######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 12 16:00:26 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

#include additional compiler info for OpenCV 
include(opencv.pro)

# Input
HEADERS +=  VideoWidget.h \
    mainwindow.h
SOURCES += main.cpp VideoWidget.cpp \
    mainwindow.cpp

FORMS += \
    mainwindow.ui
